import fs from 'node:fs/promises';
const need=['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REFRESH_TOKEN'];for(const k of need)if(!process.env[k])throw new Error(`Missing ${k}`);
const reg=JSON.parse(await fs.readFile('registry.json','utf8'));const siteUrl=reg.machine.searchConsoleProperty||'sc-domain:barbph.com';
const tokenRes=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:process.env.GOOGLE_REFRESH_TOKEN,grant_type:'refresh_token'})});if(!tokenRes.ok)throw new Error(`OAuth refresh failed ${tokenRes.status}`);const {access_token}=await tokenRes.json();const H={Authorization:`Bearer ${access_token}`,'content-type':'application/json'};
const end=new Date();end.setUTCDate(end.getUTCDate()-2);const start=new Date(end);start.setUTCDate(start.getUTCDate()-27);const ds=d=>d.toISOString().slice(0,10);
async function query(body){const r=await fetch(`https://searchconsole.googleapis.com/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/searchAnalytics/query`,{method:'POST',headers:H,body:JSON.stringify(body)});if(!r.ok)throw new Error(`Search Analytics ${r.status}: ${await r.text()}`);return r.json()}
const aggregate=await query({startDate:ds(start),endDate:ds(end),type:'web',rowLimit:1});const a=aggregate.rows?.[0]||{};
const pages=await query({startDate:ds(start),endDate:ds(end),type:'web',dimensions:['page'],rowLimit:25000});const queries=await query({startDate:ds(start),endDate:ds(end),type:'web',dimensions:['query'],rowLimit:25});
const pageMap=new Map((pages.rows||[]).map(r=>[r.keys?.[0],r]));const properties=[];let indexed=0;for(const p of reg.properties){if(!p.url){properties.push({id:p.id,name:p.name,url:null,indexVerdict:'NO URL'});continue}let ix=null;try{const ir=await fetch('https://searchconsole.googleapis.com/v1/urlInspection/index:inspect',{method:'POST',headers:H,body:JSON.stringify({inspectionUrl:p.url,siteUrl,languageCode:'en-US'})});if(ir.ok)ix=(await ir.json()).inspectionResult?.indexStatusResult||null}catch{};if(ix?.verdict==='PASS')indexed++;const perf=pageMap.get(p.url)||pageMap.get(p.url.replace(/\/$/,''))||null;properties.push({id:p.id,name:p.name,url:p.url,clicks:perf?.clicks??0,impressions:perf?.impressions??0,ctr:perf?.ctr??0,position:perf?.position??null,indexVerdict:ix?.verdict||'UNKNOWN',coverageState:ix?.coverageState||null,lastCrawlTime:ix?.lastCrawlTime||null,pageFetchState:ix?.pageFetchState||null,robotsTxtState:ix?.robotsTxtState||null,indexingState:ix?.indexingState||null,googleCanonical:ix?.googleCanonical||null,userCanonical:ix?.userCanonical||null})}
let sitemaps=[];try{const r=await fetch(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/sitemaps`,{headers:H});if(r.ok)sitemaps=(await r.json()).sitemap||[]}catch{}
const sitemapStatus=sitemaps.some(s=>!s.errors&&!s.warnings)?'success':sitemaps.length?'warning':'none';const out={generatedAt:new Date().toISOString(),source:'GOOGLE SEARCH CONSOLE',status:'connected',property:siteUrl,period:{startDate:ds(start),endDate:ds(end)},summary:{clicks:a.clicks??0,impressions:a.impressions??0,ctr:a.ctr??0,position:a.position??null,indexed,total:reg.properties.length,sitemapStatus},properties,queries:(queries.rows||[]).map(r=>({query:r.keys?.[0],clicks:r.clicks,impressions:r.impressions,ctr:r.ctr,position:r.position})),sitemaps:sitemaps.map(s=>({path:s.path,lastSubmitted:s.lastSubmitted,lastDownloaded:s.lastDownloaded,isPending:s.isPending,isSitemapsIndex:s.isSitemapsIndex,type:s.type,warnings:s.warnings,errors:s.errors}))};await fs.writeFile('data/google-search-console.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out.summary));
